name: ci-test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres
        # Provide the password for postgres
        env:
          POSTGRES_USER: root
          POSTGRES_DB: simple_bank
          POSTGRES_PASSWORD: secret
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - uses: actions/checkout@v3

    - name: Run migrations
      run: make migrateup

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18

    # not neccessary because the application will be
    # built automatically when test
    # - name: Build
    #   run: go build -v ./...

    - name: Test
      run: make test
